name: templateflutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # FIREBASE (EXCLUYE firebase_auth)
  shared_preferences: ^2.2.2
  latlong2: ^0.9.1
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.1.0
  firebase_crashlytics: ^4.0.1
  firebase_performance: ^0.10.1

  # UI BÁSICO
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.0

  # GEO / HTTP / ARCHIVOS
  image_picker: ^1.2.0
  http: ^1.2.2
  path_provider: ^2.1.5
  open_filex: ^4.5.0

  crypto: ^3.0.3

  # STATE MANAGEMENT / APIs
  provider: ^6.1.2
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1

  # BASE DE DATOS LOCAL
  sqflite: ^2.3.3+1
  path: ^1.9.0
  sqflite_live: ^1.0.1

  # PDF / FECHAS
  pdf: ^3.11.1
  printing: ^5.13.4
  intl: ^0.19.0

  # GEOLOCALIZACIÓN / MAPAS / URL
  geolocator: ^13.0.1
  geocoding: ^2.2.0
  google_maps_flutter: ^2.7.0
  url_launcher: ^6.3.0
  flutter_map: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# CONFIGURACIÓN DEL GENERADOR DE ÍCONOS
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/appimage.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
